### ISSUE TITLE
HRESULT 0x80070057 on LaunchAdvancedAssociationUI

### ISSUE THREAD

**Issue by jdehaan** [WildGums/Orc.FileAssociation#1]
On Windows 7 Professional OS, .NET 4.0 running the provided example fails at

> Orc.FileAssociation\Orc.FileAssociation.Shared\Services\FileAssociationService.cs

``` csharp
var applicationAssociationRegistrationUi = (IApplicationAssociationRegistrationUI)new   ApplicationAssociationRegistrationUI();
            var hr = applicationAssociationRegistrationUi.LaunchAdvancedAssociationUI(applicationName);
```

The COM component returns HRESULT 0x80070057.

**Comment by GeertvanHorrik** [comment]
Interested in doing a fix and PR? I have no win 7 machine to test, not really looking forward creating a win 7 vm at the moment.

**Comment by jdehaan** [comment]
Yes I am :-) I can test that is no problem but I have no clue what is going on. We tried on our own code desperately (already spend more than 10 hours in investigating and looking for solutions) Do you have a clue why this COM call seems to be a problem?

A hint is enough if I have a new idea then I can implement and test.

**Comment by jdehaan** [comment]
I forgot to mention one hint could be that the appplication is in the registry in the list of registered programs but in the Microsoft GUI it does not appear (if started manually). This could be a good hint that something is missing...

**Comment by GeertvanHorrik** [comment]
On all machines or just 1 ?

**Comment by GeertvanHorrik** [comment]
Is it a German workstation?

**Comment by GeertvanHorrik** [comment]
0x80070057 = E_INVALIDARG = One or more arguments are not valid

**Comment by jdehaan** [comment]
German locale and English version on several machines (3 tested, 3 failed) I found the meaning in MSDN docs also but it's not clear what arguments. I just give one argument, the name of the registered app. I thought again about it I'll go systematically through by checking:

1- if it works for another registered app I can see in the MS GUI if manually started
2- look at the differences in the settings in the registry

Then I should be able to solve that issue. It's quite late here already and I fear I'll only be able to work again on that topic next week. Thanks!

**Comment by jdehaan** [comment]
Had a look at it this morning, it works if I put all regkeys under HKLM... This is not a good solution. I try to find out if there is a way to make it work with keys under HKCU but it does not look promising. With ProcessMonitor I saw that windows does not even try reading out RegisteredApplications from HKCU...

**Comment by GeertvanHorrik** [comment]
The idea of putting it in HKCU is that the users can access it :-)

Weird, because the demo example works on windows 8 / windows 10.

**Comment by jdehaan** [comment]
Yes it's quite annoying... I also read that for Windows 10 changes were/are?? planned.

https://blogs.windows.com/windowsexperience/2015/05/20/announcing-windows-10-insider-preview-build-10122-for-pcs/

"We know your defaults matter to you. With Windows 10, all apps – both Classic Windows apps and Universal Windows apps – will be unable to invoke a prompt to change your defaults, only Windows. You remain in full control of your default experiences, while reducing some of the unwanted noise that multiple prompts can bring."

Would you agree to have an opt-in "legacy mode": in order to make these application registration "manually" I know this is not recommended by MS but it seems the only way to be able to do it without rights elevation...

It rather sounds that making such registrations via the application itself is somehow deemed to be a dead end in future...

**Comment by GeertvanHorrik** [comment]
About the windows 10 thing: that's how it already works from the first official build (10240). I decided to stick with the windows standards, so the code in this library will use what the user is used to on his/her system.

What this code does (even when windows just shows a dummy message) is adding it in the registry so windows *knows* that your app can open specific file names (this is still a requirement).

**Comment by jdehaan** [comment]
I see. Maybe there are also some domain policies playing in the game... It's now xmas time I'll check if this is a possible issue why user registered apps seem to not be recognized...

**Comment by GeertvanHorrik** [comment]
You don't have a non-restrictive Win 7 machine lying around where you can run the example at? I will see if I can find someone, but it might even be easier to create a vm, but earliest will be new year.

**Comment by jdehaan** [comment]
I just tried in a VM on a Win 7 Pro Machine (fully patched), the example fails too in the same manner.

**Comment by jdehaan** [comment]
I restarted investigating this: it turns out (although I compiled as AnyCPU or x64) the .NET application on Windows 7 seems to insist into fetching the regkeys inside Wow6432Node. I have no clue why this is done. But fact is, if I insert the values in the registry below the Orc.FileAssociation lib works like a charm on Win7 too. Is there a chance that this can be adapted to be integrated into the library? I know Win7 is pretty old now....

`
Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\Software\Wow6432Node\Alpine]
[HKEY_CURRENT_USER\Software\Wow6432Node\Alpine\MyApp]
[HKEY_CURRENT_USER\Software\Wow6432Node\Alpine\MyApp\Capabilities]
"ApplicationDescription"="MyApp"
[HKEY_CURRENT_USER\Software\Wow6432Node\Alpine\MyApp\Capabilities\FileAssociations]
".myappext1"="MyApp"
".myappext2"="MyApp"

[HKEY_LOCAL_MACHINE\Software\Wow6432Node\Alpine]
[HKEY_LOCAL_MACHINE\Software\Wow6432Node\Alpine\MyApp]
[HKEY_LOCAL_MACHINE\Software\Wow6432Node\Alpine\MyApp\Capabilities]
"ApplicationDescription"="MyApp"
[HKEY_LOCAL_MACHINE\Software\Wow6432Node\Alpine\MyApp\Capabilities\FileAssociations]
".myappext1"="MyApp"
".myappext2"="MyApp"
`

**Comment by GeertvanHorrik** [comment]
Thanks for the investigation. Yes, we are happy to integrate this into the lib. Interested in doing a PR?

**Comment by jdehaan** [comment]
I still want to know where this comes from... Apparently this is the way it's done on Win7 = implementation of the COM service from MS is 32bit?

I used the COM/OLE Viewer 64 bit to see the interface:
it leads to "%SystemRoot%\System32\sud.dll" which in the dependecy walker is actually a 64bit DLL... So I am still quite irritated why the app (also checked to run in 64bit mode via Sysinternals Process Explorer) would like to access the Wow6432Node keys... Mysterious.

I would not like to introduce garbage into the codebase. I can also guard the additional registry entries in some if blocks if I know what makes this situation appear.

**Comment by jdehaan** [comment]
Hmmm I think I slowly got it somehow I mistakenly assumed it was running as .NET 64 bit process. Turns out I checked wrongly in Process Explorer I thought there should be an asterisk after the process name to mark them as 32bit processes (maybe it was so in an older version) by putting the right image type column I can see it is 32bit... So the situation is clearer now. I think I can provide a clean fix. The registry view should probably be 32bit in the case of a 32 bit process running on a 64bit machine.

I just discovered "corflags" as a tool:
`Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32
CorFlags  : 3
ILONLY    : 1
32BIT     : 1
`

I checked my project settings, everything seems actually fine for 64bit (Prefer32 bit is false and AnyCPU selected). Do you have an idea?

**Comment by jdehaan** [comment]
I cleared the flag 32BIT with corflags and suddenly also everything is fine. I then think everything is clear. I have to force the registry view to 32bit in case of the process to be 32bit since the used default seems to select 64bit in that case. But I do not know if I should do it for Win7 only or for all platforms. Maybe I am the only one to still use (mistakenly) 32bit processes.... :-(

**Comment by jdehaan** [comment]
I will provide a PR but I need some time to setup the environment correctly to compile and run the tests (Azure etc...)

**Comment by jdehaan** [comment]
Turns out it's not that simple.... The minimal set of keys I need to make it work in Win7 64bit OS & 32bit application Orc.FileAssociation.Example is:

`[HKEY_LOCAL_MACHINE\Software\RegisteredApplications]
"Orc.FileAssociation.Example"="Software\\WildGums\\Orc.FileAssociation.Example\\Capabilities"

[HKEY_LOCAL_MACHINE\Software\Wow6432Node\WildGums]

[HKEY_LOCAL_MACHINE\Software\Wow6432Node\WildGums\Orc.FileAssociation.Example]

[HKEY_LOCAL_MACHINE\Software\Wow6432Node\WildGums\Orc.FileAssociation.Example\Capabilities]
"ApplicationDescription"="Orc.FileAssociation.Example"

[HKEY_LOCAL_MACHINE\Software\Wow6432Node\WildGums\Orc.FileAssociation.Example\Capabilities\FileAssociations]
".abc"="Orc.FileAssociation.Example"
".xyz"="Orc.FileAssociation.Example"
".txt"="Orc.FileAssociation.Example"
`

Unfortunately in order to do that, elevated privileges are required. I cannot really believe this is intentional from Microsoft... However I could find nothing really matching this problem in google to get deeper insight or a kind of confirmation.

**Comment by jdehaan** [comment]
Does the code work on Windows 10? From what I read this only starts a dialog with a hint on how to do it manually.

One outcome out of this dilemma could be to create several alternative implementations of the interfaces which are initialized in the ModuleInitializer based on some criteria (and/or configuration?)

`
        var os = Environment.OSVersion;
        switch (os.VersionString)
        {
            case "Microsoft Windows NT 6.1.7601 Service Pack 1":
                serviceLocator.RegisterType<IApplicationRegistrationService, ApplicationRegistrationServiceWin7>();
                serviceLocator.RegisterType<IFileAssociationService, FileAssociationViaComService>();
                break;
            default:
                serviceLocator.RegisterType<IApplicationRegistrationService, ApplicationRegistrationService>();
                serviceLocator.RegisterType<IFileAssociationService, FileAssociationViaComService>();
                break;
        }
`

I did not think this topic would be so hard. I unfortunately quit due to workload that topic for the moment being.

**Comment by mkhomutov** [comment]
![image](https://cloud.githubusercontent.com/assets/1632214/22343535/7f1e20a8-e409-11e6-8f65-b1d46e154cee.png)
that's what you will see in Win 10
