### ISSUE TITLE
Update documentation on the website

### ISSUE THREAD

**Issue by jornane** [WildGums/Orc.FileAssociation#218]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?

Documentation

## Version of Library

4.0.1

## Version of OS(s) listed above with issue

Windows 10

## Steps to Reproduce
1. Visit https://opensource.wildgums.com/orc.fileassociation/
2. Use code from documentation
3. Get errors from Visual Studio that function name is wrong

## Expected Behavior
The function names in the documentation should be updated to reflect the actual function names

* **Unregistering an application** should be done by calling `_applicationRegistrationService.UnregisterApplication`, documentation states `_applicationRegistrationService.RegisterApplication`
* **Updating a registered application** should be done by calling `_applicationRegistrationService.UpdateRegistration`, documentation states `_applicationRegistrationService.UpdateApplication`

## Actual Behavior
The function names are wrong and thus the code cannot compile, or would work unexpectedly without making manual fixes

Thanks for the great library! <3

**Comment by GeertvanHorrik** [comment]
Thanks for the feedback!

**Comment by GeertvanHorrik** [comment]
Done, documentation should auto-update itself within 15 minutes. Again, thanks for reporting.
